apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: abjs1zj1w-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/abjs1zj1w-dotnet-basic-gitops